services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PROPERTY_USER_PASSWORD=${DB_PROPERTY_USER_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - qrent-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$DB_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s


  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    env_file:
      - .env
    ports:
      - '${BACKEND_LISTEN_PORT:-3200}:${BACKEND_LISTEN_PORT:-3200}'
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - qrent-network

networks:
  qrent-network:

volumes:
  db_data:
