name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Setup environment file
      run: |
        cp .env.example .env

    - name: Build and start services
      run: |
        docker compose build
        docker compose up -d

    - name: Run tests in container
      run: |
        docker compose exec -T backend pnpm test:backend

    - name: Cleanup
      if: always()
      run: docker compose down
